### ISSUE TITLE
Allow Instrument Window Resize

### ISSUE THREAD

**Issue by TreeBaron** [bastibe/MiniHUD#2]
Hello, thank you for the plugin. 

I game on a 4k TV that is a decent distance away from me, and I struggled to read the Mini HUD but it does not allow resizing of the window. I thought maybe it was a scaling issue at first due to hard-coded graphical values, but I modified the plugin on my machine and it seems to resize just fine.

I do not have permission to create a pull-request, but I'd like to request that you set noResize to false, and proportional to true so that users on 4K displays, or those with poor vision can easily increase the size of the HUD.

From main.lua line 10:

```
local instrumentWindow = contextWindow {
    name = "Instrument HUD";
    position = { 50, 50, 450, 200 };
    saveState = false;
    noDecore = true;
    noBackground = true;
    noResize = false;
    visible = true;
    proportional = true;
    gravity = {0, 0, 0, 0}; -- stick to the left bottom
    vrAuto = true;
    layer = SASL_CW_LAYER_FLIGHT_OVERLAY;
    components = {
        instrumentPanel {
            position = { 0, 0, 450, 200 };
        }
    }
}
```

Thanks!

**Comment by bastibe** [comment]
Thank you for the feature request!

Unfortunately, I wrote the entire plugin with hard-coded pixel layouts. You can indeed resize the windows as you see fit if you set `noResize = false;`, but that just stretches the pixels and makes everything look blurry. This is probably completely fine for your use case, but it will no doubt annoy many others.

In your case, however, you could decrease the resolution of X-Plane entirely, which would scale up every UI item, including the MiniHUD.

Implementing this properly would require rewriting all the layouts independent of the pixel scale, which would take more time than I can currently spare. If you'd like to help do that, however, I'd be happy to accept a pull request.

Thank you for reaching out!

**Comment by TreeBaron** [comment]
@bastibe Hello,
I have a branch which addresses your concerns regarding resizing the window. I just need some permissions so I can push the feature branch and create a pull request.

Here are 2 example screenshots at different resolutions.
![1024by768Screenshot](https://github.com/user-attachments/assets/baff8726-9300-4010-99d0-3a5cf587ff70)
![1920by1080screenshot](https://github.com/user-attachments/assets/f674d4d6-5f09-4387-926b-d5eaac8c0e25)

Changes:

- MiniHUD will now scale dynamically based on the user's vertical resolution
- MiniHUD can now be resized, it will maintain its aspect ratio and has had its font size doubled from 12 to 24 thus allowing it to be scaled up and still look crisp even at 4K resolution (screenshot was too large for github to accept but I can include it in my branch)

Code Changes:
Originally I had planned on just increasing the font-size, and then scaling down the font by default and having it scale upwards as the window size increased. I eventually got this working but there were too many magic numbers and some things like font-centering just didn't work quite right. It was still fine until I reached the compass at which point I scrapped this approach.
For my second approach, I just doubled the font size, set the window to be large on my screen but have the same ratio and started changing hard coded values with references to a few predetermined ratios (e.g. 1/100th of window height). Even with this approach though there were still some scaling issues so the final approach I landed on is as-follows:
The window starts at a set height and width, these are the values I used when I redid the visuals with the larger font size. When the program starts, it looks at the user's screen resolution and determines a scale number based on the height of the user's screen relative to 1080 vertical pixels. 
On first update, the program will scale proportionally down to the ratio that was determined at startup based on a user's screen resolution. Theoretically it will take up the same real-estate on any screen with the same aspect ratio, regardless of resolution.
I added a variable also so you can tweak how much screen real-estate the HUD takes up. This will not interfere with the automatic scaling it will just change the ratio of the window relative to the resolution which is available.

**Comment by bastibe** [comment]
Beautiful! Thank you very much!

> I just need some permissions so I can push the feature branch and create a pull request.

What do you need from me? Typically, you'd fork the repository, and push your changes to a new branch on your fork. This can be sent as a pull request to this here repository.

**Comment by TreeBaron** [comment]
> Beautiful! Thank you very much!
> 
> > I just need some permissions so I can push the feature branch and create a pull request.
> 
> What do you need from me? Typically, you'd fork the repository, and push your changes to a new branch on your fork. This can be sent as a pull request to this here repository.

Ah, that makes sense, thanks.

Pull Request has been submitted.

**Comment by bastibe** [comment]
Thank you so much! I'll have a look in the next few days.
